// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace PGBtesting
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// LoginMethod - Use 'LoginMethodParams' to pass parameters into this method.
        /// </summary>
        public void LoginMethod()
        {
            #region Variable Declarations
            HtmlCustom uITargetCustom = this.UIHttpadminqab1beneshaWindow.UIHttpadminqab1beneshaDocument.UITargetCustom;
            HtmlEdit uILoginIdEdit = this.UIHttpadminqab1beneshaWindow.UIHttpadminqab1beneshaDocument.UILoginIdEdit;
            HtmlEdit uIPasswordEdit = this.UIHttpadminqab1beneshaWindow.UIHttpadminqab1beneshaDocument.UIPasswordEdit;
            HtmlHyperlink uISubGroupHyperlink = this.UIHttpadminqab1beneshaWindow.UIHttpadminqab1beneshaDocument1.UINotificationsCustom.UISubGroupHyperlink;
            HtmlButton uIEmployeeManagementButton = this.UIHttpadminqab1beneshaWindow.UIHttpadminqab1beneshaDocument2.UIDvSubGroupPane.UIEmployeeManagementButton;
            HtmlButton uISearchButton = this.UIHttpadminqab1beneshaWindow.UIHttpadminqab1beneshaDocument3.UISearchButton;
            HtmlButton uIAddEmployeeButton = this.UIHttpadminqab1beneshaWindow.UIHttpadminqab1beneshaDocument4.UIAddEmployeeButton;
            #endregion

            // Click 'target' custom control
            Mouse.Click(uITargetCustom, new Point(267, 69));

            // Type 'Nikunj' in 'LoginId' text box
            uILoginIdEdit.Text = this.LoginMethodParams.UILoginIdEditText;

            // Type '{Tab}' in 'LoginId' text box
            Keyboard.SendKeys(uILoginIdEdit, this.LoginMethodParams.UILoginIdEditSendKeys, ModifierKeys.None);

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LoginMethodParams.UIPasswordEditPassword;

            // Type '{Enter}' in 'Password' text box
            Keyboard.SendKeys(uIPasswordEdit, this.LoginMethodParams.UIPasswordEditSendKeys, ModifierKeys.None);

            // Click 'Sub Group' link
            Mouse.Click(uISubGroupHyperlink, new Point(25, 5));

            // Click 'Employee Management' button
            Mouse.Click(uIEmployeeManagementButton, new Point(62, 13));

            // Click 'Search' button
            Mouse.Click(uISearchButton, new Point(60, 39));

            // Click 'Add Employee' button
            Mouse.Click(uIAddEmployeeButton, new Point(30, 21));
        }
        
        #region Properties
        public virtual LoginMethodParams LoginMethodParams
        {
            get
            {
                if ((this.mLoginMethodParams == null))
                {
                    this.mLoginMethodParams = new LoginMethodParams();
                }
                return this.mLoginMethodParams;
            }
        }
        
        public UIHttpadminqab1beneshaWindow UIHttpadminqab1beneshaWindow
        {
            get
            {
                if ((this.mUIHttpadminqab1beneshaWindow == null))
                {
                    this.mUIHttpadminqab1beneshaWindow = new UIHttpadminqab1beneshaWindow();
                }
                return this.mUIHttpadminqab1beneshaWindow;
            }
        }
        #endregion
        
        #region Fields
        private LoginMethodParams mLoginMethodParams;
        
        private UIHttpadminqab1beneshaWindow mUIHttpadminqab1beneshaWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LoginMethod'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class LoginMethodParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Nikunj' in 'LoginId' text box
        /// </summary>
        public string UILoginIdEditText = "Nikunj";
        
        /// <summary>
        /// Type '{Tab}' in 'LoginId' text box
        /// </summary>
        public string UILoginIdEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "Pdjhf/QhLq+svb0gRChZuF9pP2AoyRe/";
        
        /// <summary>
        /// Type '{Enter}' in 'Password' text box
        /// </summary>
        public string UIPasswordEditSendKeys = "{Enter}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHttpadminqab1beneshaWindow : BrowserWindow
    {
        
        public UIHttpadminqab1beneshaWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "http://admin.qab1.beneshark.com/Identity/Login?ReturnUrl=%2f";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/Identity/Login?ReturnUrl=%2f");
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/");
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/MasterData/SubGroup");
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/EmployeeManagement/Employee");
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/EmployeeManagement/Employee/EmployeeSearchResult?" +
                    "__RequestVerif");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpadminqab1beneshaDocument UIHttpadminqab1beneshaDocument
        {
            get
            {
                if ((this.mUIHttpadminqab1beneshaDocument == null))
                {
                    this.mUIHttpadminqab1beneshaDocument = new UIHttpadminqab1beneshaDocument(this);
                }
                return this.mUIHttpadminqab1beneshaDocument;
            }
        }
        
        public UIHttpadminqab1beneshaDocument1 UIHttpadminqab1beneshaDocument1
        {
            get
            {
                if ((this.mUIHttpadminqab1beneshaDocument1 == null))
                {
                    this.mUIHttpadminqab1beneshaDocument1 = new UIHttpadminqab1beneshaDocument1(this);
                }
                return this.mUIHttpadminqab1beneshaDocument1;
            }
        }
        
        public UIHttpadminqab1beneshaDocument2 UIHttpadminqab1beneshaDocument2
        {
            get
            {
                if ((this.mUIHttpadminqab1beneshaDocument2 == null))
                {
                    this.mUIHttpadminqab1beneshaDocument2 = new UIHttpadminqab1beneshaDocument2(this);
                }
                return this.mUIHttpadminqab1beneshaDocument2;
            }
        }
        
        public UIHttpadminqab1beneshaDocument3 UIHttpadminqab1beneshaDocument3
        {
            get
            {
                if ((this.mUIHttpadminqab1beneshaDocument3 == null))
                {
                    this.mUIHttpadminqab1beneshaDocument3 = new UIHttpadminqab1beneshaDocument3(this);
                }
                return this.mUIHttpadminqab1beneshaDocument3;
            }
        }
        
        public UIHttpadminqab1beneshaDocument4 UIHttpadminqab1beneshaDocument4
        {
            get
            {
                if ((this.mUIHttpadminqab1beneshaDocument4 == null))
                {
                    this.mUIHttpadminqab1beneshaDocument4 = new UIHttpadminqab1beneshaDocument4(this);
                }
                return this.mUIHttpadminqab1beneshaDocument4;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpadminqab1beneshaDocument mUIHttpadminqab1beneshaDocument;
        
        private UIHttpadminqab1beneshaDocument1 mUIHttpadminqab1beneshaDocument1;
        
        private UIHttpadminqab1beneshaDocument2 mUIHttpadminqab1beneshaDocument2;
        
        private UIHttpadminqab1beneshaDocument3 mUIHttpadminqab1beneshaDocument3;
        
        private UIHttpadminqab1beneshaDocument4 mUIHttpadminqab1beneshaDocument4;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHttpadminqab1beneshaDocument : HtmlDocument
    {
        
        public UIHttpadminqab1beneshaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Identity/Login";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://admin.qab1.beneshark.com/Identity/Login?ReturnUrl=%2f";
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/Identity/Login?ReturnUrl=%2f");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UITargetCustom
        {
            get
            {
                if ((this.mUITargetCustom == null))
                {
                    this.mUITargetCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUITargetCustom.SearchProperties["TagName"] = "FORM";
                    this.mUITargetCustom.SearchProperties["Id"] = "target";
                    this.mUITargetCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUITargetCustom.FilterProperties["Class"] = "form";
                    this.mUITargetCustom.FilterProperties["ControlDefinition"] = "class=\"form\" id=\"target\" role=\"form\" ons";
                    this.mUITargetCustom.FilterProperties["TagInstance"] = "1";
                    this.mUITargetCustom.WindowTitles.Add("http://admin.qab1.beneshark.com/Identity/Login?ReturnUrl=%2f");
                    #endregion
                }
                return this.mUITargetCustom;
            }
        }
        
        public HtmlEdit UILoginIdEdit
        {
            get
            {
                if ((this.mUILoginIdEdit == null))
                {
                    this.mUILoginIdEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILoginIdEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "txtLoginId";
                    this.mUILoginIdEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "LoginId";
                    this.mUILoginIdEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILoginIdEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILoginIdEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILoginIdEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUILoginIdEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"LoginId\" class=\"form-control\" id=\"";
                    this.mUILoginIdEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUILoginIdEdit.WindowTitles.Add("http://admin.qab1.beneshark.com/Identity/Login?ReturnUrl=%2f");
                    #endregion
                }
                return this.mUILoginIdEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "txtPassword";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "form-control";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"Password\" class=\"form-control\" id=";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "5";
                    this.mUIPasswordEdit.WindowTitles.Add("http://admin.qab1.beneshark.com/Identity/Login?ReturnUrl=%2f");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUITargetCustom;
        
        private HtmlEdit mUILoginIdEdit;
        
        private HtmlEdit mUIPasswordEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHttpadminqab1beneshaDocument1 : HtmlDocument
    {
        
        public UIHttpadminqab1beneshaDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://admin.qab1.beneshark.com/";
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/");
            #endregion
        }
        
        #region Properties
        public UINotificationsCustom UINotificationsCustom
        {
            get
            {
                if ((this.mUINotificationsCustom == null))
                {
                    this.mUINotificationsCustom = new UINotificationsCustom(this);
                }
                return this.mUINotificationsCustom;
            }
        }
        #endregion
        
        #region Fields
        private UINotificationsCustom mUINotificationsCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UINotificationsCustom : HtmlCustom
    {
        
        public UINotificationsCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "SECTION";
            this.SearchProperties["Id"] = "notifications";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"notifications\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UISubGroupHyperlink
        {
            get
            {
                if ((this.mUISubGroupHyperlink == null))
                {
                    this.mUISubGroupHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUISubGroupHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUISubGroupHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUISubGroupHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUISubGroupHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Sub Group";
                    this.mUISubGroupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/MasterData/SubGroup";
                    this.mUISubGroupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUISubGroupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://admin.qab1.beneshark.com/MasterData/SubGroup";
                    this.mUISubGroupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUISubGroupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/MasterData/SubGroup\"";
                    this.mUISubGroupHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "11";
                    this.mUISubGroupHyperlink.WindowTitles.Add("http://admin.qab1.beneshark.com/");
                    #endregion
                }
                return this.mUISubGroupHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUISubGroupHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHttpadminqab1beneshaDocument2 : HtmlDocument
    {
        
        public UIHttpadminqab1beneshaDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/MasterData/SubGroup";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://admin.qab1.beneshark.com/MasterData/SubGroup";
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/MasterData/SubGroup");
            #endregion
        }
        
        #region Properties
        public UIDvSubGroupPane UIDvSubGroupPane
        {
            get
            {
                if ((this.mUIDvSubGroupPane == null))
                {
                    this.mUIDvSubGroupPane = new UIDvSubGroupPane(this);
                }
                return this.mUIDvSubGroupPane;
            }
        }
        #endregion
        
        #region Fields
        private UIDvSubGroupPane mUIDvSubGroupPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDvSubGroupPane : HtmlDiv
    {
        
        public UIDvSubGroupPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "dvSubGroup";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Igate Subgroup one\r\n\r\nAuto Submit Auto S";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "col-md-12";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"col-md-12\" id=\"dvSubGroup\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "30";
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/MasterData/SubGroup");
            #endregion
        }
        
        #region Properties
        public HtmlButton UIEmployeeManagementButton
        {
            get
            {
                if ((this.mUIEmployeeManagementButton == null))
                {
                    this.mUIEmployeeManagementButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIEmployeeManagementButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIEmployeeManagementButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIEmployeeManagementButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = " Employee Management ";
                    this.mUIEmployeeManagementButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIEmployeeManagementButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIEmployeeManagementButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary btn-outline btn-xs ";
                    this.mUIEmployeeManagementButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary btn-outline btn-x";
                    this.mUIEmployeeManagementButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "6";
                    this.mUIEmployeeManagementButton.WindowTitles.Add("http://admin.qab1.beneshark.com/MasterData/SubGroup");
                    #endregion
                }
                return this.mUIEmployeeManagementButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUIEmployeeManagementButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHttpadminqab1beneshaDocument3 : HtmlDocument
    {
        
        public UIHttpadminqab1beneshaDocument3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/EmployeeManagement/Employee";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://admin.qab1.beneshark.com/EmployeeManagement/Employee";
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/EmployeeManagement/Employee");
            #endregion
        }
        
        #region Properties
        public HtmlButton UISearchButton
        {
            get
            {
                if ((this.mUISearchButton == null))
                {
                    this.mUISearchButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Id] = "btnSearch";
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = " Search";
                    this.mUISearchButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-primary searchBtn";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-primary searchBtn\" id=\"bt";
                    this.mUISearchButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "2";
                    this.mUISearchButton.WindowTitles.Add("http://admin.qab1.beneshark.com/EmployeeManagement/Employee");
                    #endregion
                }
                return this.mUISearchButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUISearchButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHttpadminqab1beneshaDocument4 : HtmlDocument
    {
        
        public UIHttpadminqab1beneshaDocument4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/EmployeeManagement/Employee/EmployeeSearchResult";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://admin.qab1.beneshark.com/EmployeeManagement/Employee/EmployeeSearchResult?" +
                "__RequestVerificationToken=KdYEvFO-BB6U2HmnSzqzhfCKt6zPoor7iUHusCJqkhyhifdBge4be" +
                "VZrkYToN0DrolEeDeEkzsQn92jS9dpWmZ_sXNY3ILFNY_n4VywE2A81&searchText=";
            this.WindowTitles.Add("http://admin.qab1.beneshark.com/EmployeeManagement/Employee/EmployeeSearchResult?" +
                    "__RequestVerif");
            #endregion
        }
        
        #region Properties
        public HtmlButton UIAddEmployeeButton
        {
            get
            {
                if ((this.mUIAddEmployeeButton == null))
                {
                    this.mUIAddEmployeeButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIAddEmployeeButton.SearchProperties[HtmlButton.PropertyNames.Id] = "addEmployee";
                    this.mUIAddEmployeeButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIAddEmployeeButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = " Add Employee ";
                    this.mUIAddEmployeeButton.SearchProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-warning pull-right";
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-warning pull-right\" id=\"a";
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "3";
                    this.mUIAddEmployeeButton.WindowTitles.Add("http://admin.qab1.beneshark.com/EmployeeManagement/Employee/EmployeeSearchResult?" +
                            "__RequestVerif");
                    #endregion
                }
                return this.mUIAddEmployeeButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUIAddEmployeeButton;
        #endregion
    }
}
